---
title: "25genes_isofrac"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(SummarizedExperiment)
library(dplyr)
```
load the tx object I saved earlier and calculate isoform fractions from TPM
```{r}
load("data/rse_tx.25g.n2844.Rdata")
```

```{r}
tpms <- as.data.frame(assay(rse_tx))

tpms$transcript_id <- rownames(tpms)
addCols <- c('transcript_id', 'gene_id')
tpms <- dplyr::select(left_join(tpms, as.data.frame(rowData(rse_tx))[, addCols], by = 'transcript_id'), 
                     all_of(addCols), everything())
rownames(tpms) <- tpms$transcript_id
ns <- length(addCols)+1
nc <- ncol(tpms)
csel <- seq(ns, nc) #numeric data columns 
## -- get sum of TPMs for each gene
gsum <- as.data.frame( rowsum(x=tpms[, csel], group=tpms$gene_id ) )
gsum$gene_id <- rownames(gsum)
rownames(gsum) <- NULL
## -- compute isoform fractions

gsum <- dplyr::inner_join(
            tpms[,c('transcript_id','gene_id')],
            gsum,
            by='gene_id')
## make sure row order matches
if (! all.equal(tpms$transcript_id, gsum$transcript_id)) {
  message("Reordering gsum..")
  gsum <- gsum[match(tpms$transcript_id, gsum$transcript_id), ]
}
rownames(gsum) <- gsum$transcript_id
isofrac <- round( tpms[, csel]/gsum[, csel], digits=2)
# replace NaN with 0 and add two columns for inspection
isofrac <- isofrac %>% mutate_all(~replace(., is.nan(.), 0))

#isofrac$gene_id <- tpms$gene_id
## reorder columns to see gene_id before the numeric columns
#isofrac <- dplyr::select(isofrac, c('gene_id'), everything())

assay(rse_tx, "isofrac") <- as.matrix(isofrac)

#save(rse_tx, file="rse_tx.25g.w_isofrac.n2844.Rdata")
```

Let's get the average isoform fractions per brain region, cauc > 17y, controls only
I'll split DLPFC in DLPFC_polyA and DLPFC_ribo just to contemplate the difference

```{r}
tgfactor<-factor(levels=c('CNNM1','GBF1','KCNQ3','RAB3A','RGAG4','ATP1A3','NOS1AP','UBE2O','GPR179',
'UNC79','RPH3A','CACNA2D2','HECTD4','C22orf29','HECW1','DLGAP2','SYN1','ATP2A2','MKL1','SLC7A8',
'KCNMA1','HSD3BP4','HSD3BP5','PIGCP1','RP11-64K12.10'))
```


```{r}

getIsoFractions <- function(rse17cauc, region, dx) {
  rse <- rse17cauc[, rse17cauc$Dx==dx]
  ns <- ncol(rse)
  ifm <- as.data.frame(rowMeans(assay(rse, "isofrac")))
  colnames(ifm) <- c('if_avg')
  ifm$transcript_id <- rownames(ifm)
  # there is no reason for the order to change
  if (! all.equal(rowData(rse)$transcript_id, ifm$transcript_id) ) {
    message("Rows out of order -- fixing")
    ifm <- ifm[ match(rowData(rse)$transcript_id, ifm$transcript_id), ]
  }
  # add some informative columns
  ifm$tgene <- factor(rowData(rse)$tgene, levels=levels(tgfactor))
  ifm$gene_name <- rowData(rse)$gene_name
  ifm$gene_id <- rowData(rse)$gene_id
  ifm$transcript_name <- rowData(rse)$transcript_name
  # rearrange columns in a more meaningful way
  # --
  # keep top 3 isoforms, change n=3 to n=5 if you want more
  srtifm <- as.data.frame(ifm %>% mutate(if_avg = round(if_avg, digits=2)) %>% 
                  group_by(tgene) %>% mutate(tx_count=n()) %>% 
                  slice_max(order_by=if_avg, n=3) %>% slice_head(n=3) %>%
                    select('tgene', 'gene_id', 'gene_name', 'tx_count', 
                           'transcript_id', 'transcript_name','if_avg') )
  write.csv(srtifm, file=paste0(region,".",dx,".n",ns,".isofrac_top3.csv"), quote = F, row.names = F)
}
```


```{r}

rsesub <- rse_tx[, rse_tx$Age>17 & rse_tx$Race=='CAUC']
## 487 samples
#table(rsesub$Region)
#       Caudate DentateGyrus        DLPFC        HIPPO         mPFC 
#         118           43          177          110           39 

## 1. DLPFC polyA
for (dx in c('Control', 'Schizo')) {
 getIsoFractions(rsesub[, rsesub$Dataset=="BrainSeq_Phase1"], "DLPFC_polyA", dx)
 ## 2. DLPFC ribo
 getIsoFractions(rsesub[, rsesub$Region=="DLPFC" & rsesub$Dataset!="BrainSeq_Phase1"], "DLPFC_ribo", dx)
 ## 3. HIPPO
 getIsoFractions(rsesub[, rsesub$Region=="HIPPO"], "HIPPO", dx)
 ## 4. Caudate
 getIsoFractions(rsesub[, rsesub$Region=="Caudate"], "Caudate", dx)
 ## 5. DentateGyrus
 getIsoFractions(rsesub[, rsesub$Region=="DentateGyrus"], "DG", dx)
 ## 6. mPFC
 getIsoFractions(rsesub[, rsesub$Region=="mPFC"], "mPFC", dx)
}
```

